export const WorldLifeExpectancy2021 = [
    {
        currentPosition: 1,
        country: "Hong Kong",
        femaleLifeExpectancyWeeks: 4600,
        maleLifeExpectancyWeeks: 4298,
    },
    {
        currentPosition: 2,
        country: "Japan",
        femaleLifeExpectancyWeeks: 4596,
        maleLifeExpectancyWeeks: 4274,
    },
    {
        currentPosition: 3,
        country: "Macao",
        femaleLifeExpectancyWeeks: 4572,
        maleLifeExpectancyWeeks: 4264,
    },
    {
        currentPosition: 4,
        country: "Switzerland",
        femaleLifeExpectancyWeeks: 4488,
        maleLifeExpectancyWeeks: 4300,
    },
    {
        currentPosition: 5,
        country: "Singapore",
        femaleLifeExpectancyWeeks: 4495,
        maleLifeExpectancyWeeks: 4282,
    },
    {
        currentPosition: 6,
        country: "Italy",
        femaleLifeExpectancyWeeks: 4486,
        maleLifeExpectancyWeeks: 4273,
    },
    {
        currentPosition: 7,
        country: "Spain",
        femaleLifeExpectancyWeeks: 4523,
        maleLifeExpectancyWeeks: 4240,
    },
    {
        currentPosition: 8,
        country: "Australia",
        femaleLifeExpectancyWeeks: 4477,
        maleLifeExpectancyWeeks: 4477,
    },
    {
        currentPosition: 9,
        country: "Channel Islands",
        femaleLifeExpectancyWeeks: 4451,
        maleLifeExpectancyWeeks: 4269,
    },
    {
        currentPosition: 10,
        country: "Iceland",
        femaleLifeExpectancyWeeks: 4430,
        maleLifeExpectancyWeeks: 4286,
    },
    {
        currentPosition: 11,
        country: "South Korea",
        femaleLifeExpectancyWeeks: 4509,
        maleLifeExpectancyWeeks: 4198,
    },
    {
        currentPosition: 12,
        country: "Israel",
        femaleLifeExpectancyWeeks: 4430,
        maleLifeExpectancyWeeks: 4277,
    },
    {
        currentPosition: 13,
        country: "Sweden",
        femaleLifeExpectancyWeeks: 4433,
        maleLifeExpectancyWeeks: 4262
    },
    {
        currentPosition: 14,
        country: "France",
        femaleLifeExpectancyWeeks: 4478,
        maleLifeExpectancyWeeks: 4191,
    },
    {
        currentPosition: 15,
        country: "Malta",
        femaleLifeExpectancyWeeks: 4418,
        maleLifeExpectancyWeeks: 4246,
    },
    {
        currentPosition: 16,
        country: "Canada",
        femaleLifeExpectancyWeeks: 4421,
        maleLifeExpectancyWeeks: 4234,
    },
    {
        currentPosition: 17, country: "Norway", femaleLifeExpectancyWeeks: 4424, maleLifeExpectancyWeeks: 4232,
    },
    { currentPosition: 18, country: "Ireland", femaleLifeExpectancyWeeks: 4400, maleLifeExpectancyWeeks: 4241, },
    { currentPosition: 19, country: "New Zealand", femaleLifeExpectancyWeeks: 4403, maleLifeExpectancyWeeks: 4237, },
    { currentPosition: 19, country: "Greece", femaleLifeExpectancyWeeks: 4439, maleLifeExpectancyWeeks: 4201, },
    { currentPosition: 20, country: "Luxembourg", femaleLifeExpectancyWeeks: 4423, maleLifeExpectancyWeeks: 4217, },
    { currentPosition: 21, country: "Netherlands", femaleLifeExpectancyWeeks: 4401, maleLifeExpectancyWeeks: 4237, },
    { currentPosition: 22, country: "Guadeloupe", femaleLifeExpectancyWeeks: 4484, maleLifeExpectancyWeeks: 4130, },
    { currentPosition: 23, country: "Portugal", femaleLifeExpectancyWeeks: 4450, maleLifeExpectancyWeeks: 4163, },
    { currentPosition: 24, country: "Finland", femaleLifeExpectancyWeeks: 4442, maleLifeExpectancyWeeks: 4165, },
    { currentPosition: 25, country: "Belgium", femaleLifeExpectancyWeeks: 4399, maleLifeExpectancyWeeks: 4174, },
    { currentPosition: 26, country: "Austria", femaleLifeExpectancyWeeks: 4393, maleLifeExpectancyWeeks: 4168, },
    { currentPosition: 27, country: "Germany", femaleLifeExpectancyWeeks: 4390, maleLifeExpectancyWeeks: 4154, },
    { currentPosition: 28, country: "Slovenia", femaleLifeExpectancyWeeks: 4406, maleLifeExpectancyWeeks: 4136, },
    { currentPosition: 29, country: "United Kingdom", femaleLifeExpectancyWeeks: 4345, maleLifeExpectancyWeeks: 4186, },
    { currentPosition: 30, country: "Réunion", femaleLifeExpectancyWeeks: 4406, maleLifeExpectancyWeeks: 4097, },
    { currentPosition: 31, country: "Cyprus", femaleLifeExpectancyWeeks: 4354, maleLifeExpectancyWeeks: 4151, },
    { currentPosition: 32, country: "Denmark", femaleLifeExpectancyWeeks: 4345, maleLifeExpectancyWeeks: 4150, },
    { currentPosition: 33, country: "U.S.Virgin Islands", femaleLifeExpectancyWeeks: 4358, maleLifeExpectancyWeeks: 4103, },
    { currentPosition: 34, country: "Taiwan", femaleLifeExpectancyWeeks: 4364, maleLifeExpectancyWeeks: 4095, },
    { currentPosition: 35, country: "Costa Rica", femaleLifeExpectancyWeeks: 4351, maleLifeExpectancyWeeks: 4097, },
    { currentPosition: 36, country: "Guam", femaleLifeExpectancyWeeks: 4382, maleLifeExpectancyWeeks: 4051, },
    { currentPosition: 36, country: "Chile", femaleLifeExpectancyWeeks: 4320, maleLifeExpectancyWeeks: 4098, },
    { currentPosition: 37, country: "Qatar", femaleLifeExpectancyWeeks: 4304, maleLifeExpectancyWeeks: 4163, },
    { currentPosition: 38, country: "Puerto Rico", femaleLifeExpectancyWeeks: 4379, maleLifeExpectancyWeeks: 4032, },
    { currentPosition: 39, country: "French Guiana", femaleLifeExpectancyWeeks: 4351, maleLifeExpectancyWeeks: 4059, },
    { currentPosition: 40, country: "Maldives", femaleLifeExpectancyWeeks: 4257, maleLifeExpectancyWeeks: 4097, },
    { currentPosition: 41, country: "Mayotte", femaleLifeExpectancyWeeks: 4343, maleLifeExpectancyWeeks: 3998, },
    { currentPosition: 41, country: "Czech Republic(Czechia)", femaleLifeExpectancyWeeks: 4297, maleLifeExpectancyWeeks: 4035, },
    { currentPosition: 42, country: "Barbados", femaleLifeExpectancyWeeks: 4219, maleLifeExpectancyWeeks: 4089, },
    { currentPosition: 43, country: "Curaçao", femaleLifeExpectancyWeeks: 4283, maleLifeExpectancyWeeks: 3987, },
    { currentPosition: 44, country: "Poland", femaleLifeExpectancyWeeks: 4330, maleLifeExpectancyWeeks: 3940, },
    { currentPosition: 44, country: "Lebanon", femaleLifeExpectancyWeeks: 4235, maleLifeExpectancyWeeks: 4045, },
    { currentPosition: 45, country: "Cuba", femaleLifeExpectancyWeeks: 4233, maleLifeExpectancyWeeks: 4031, },
    { currentPosition: 45, country: "Estonia", femaleLifeExpectancyWeeks: 4334, maleLifeExpectancyWeeks: 3912, },
    { currentPosition: 46, country: "United States", femaleLifeExpectancyWeeks: 4260, maleLifeExpectancyWeeks: 3997, },
    { currentPosition: 47, country: "Panama", femaleLifeExpectancyWeeks: 4289, maleLifeExpectancyWeeks: 3973, },
    { currentPosition: 48, country: "Croatia", femaleLifeExpectancyWeeks: 4280, maleLifeExpectancyWeeks: 3963, },
    { currentPosition: 49, country: "Albania", femaleLifeExpectancyWeeks: 4199, maleLifeExpectancyWeeks: 4043, },
    { currentPosition: 50, country: "Oman", femaleLifeExpectancyWeeks: 4223, maleLifeExpectancyWeeks: 4012, },
    { currentPosition: 51, country: "United Arab Emirates", femaleLifeExpectancyWeeks: 4164, maleLifeExpectancyWeeks: 4059, },
    { currentPosition: 52, country: "Turkey", femaleLifeExpectancyWeeks: 4237, maleLifeExpectancyWeeks: 3943, },
    { currentPosition: 53, country: "Uruguay", femaleLifeExpectancyWeeks: 4272, maleLifeExpectancyWeeks: 3900, },
    { currentPosition: 54, country: "French Polynesia", femaleLifeExpectancyWeeks: 4196, maleLifeExpectancyWeeks: 3977, },
    { currentPosition: 56, country: "Slovakia", femaleLifeExpectancyWeeks: 4245, maleLifeExpectancyWeeks: 3892, },
    { currentPosition: 57, country: "Bosnia and Herzegovina", femaleLifeExpectancyWeeks: 4191, maleLifeExpectancyWeeks: 3938, },
    { currentPosition: 58, country: "Colombia", femaleLifeExpectancyWeeks: 4202, maleLifeExpectancyWeeks: 3923, },
    { currentPosition: 59, country: "Thailand", femaleLifeExpectancyWeeks: 4244, maleLifeExpectancyWeeks: 3869, },
    { currentPosition: 60, country: "Bahrain", femaleLifeExpectancyWeeks: 4116, maleLifeExpectancyWeeks: 4011, },
    { currentPosition: 61, country: "Ecuador", femaleLifeExpectancyWeeks: 4198, maleLifeExpectancyWeeks: 3916, },
    { currentPosition: 62, country: "Sri Lanka", femaleLifeExpectancyWeeks: 4213, maleLifeExpectancyWeeks: 3874, },
    { currentPosition: 63, country: "Algeria", femaleLifeExpectancyWeeks: 4109, maleLifeExpectancyWeeks: 3981, },
    { currentPosition: 64, country: "Antigua and Barbuda", femaleLifeExpectancyWeeks: 4100, maleLifeExpectancyWeeks: 3979, },
    { currentPosition: 64, country: "China", femaleLifeExpectancyWeeks: 4160, maleLifeExpectancyWeeks: 3932, },
    { currentPosition: 65, country: "Peru", femaleLifeExpectancyWeeks: 4182, maleLifeExpectancyWeeks: 3906, },
    { currentPosition: 66, country: "Morocco", femaleLifeExpectancyWeeks: 4104, maleLifeExpectancyWeeks: 3974, },
    { currentPosition: 67, country: "Montenegro", femaleLifeExpectancyWeeks: 4162, maleLifeExpectancyWeeks: 3913, },
    { currentPosition: 68, country: "Tunisia", femaleLifeExpectancyWeeks: 4140, maleLifeExpectancyWeeks: 3933, },
    { currentPosition: 69, country: "Iran", femaleLifeExpectancyWeeks: 4098, maleLifeExpectancyWeeks: 3977, },
    { currentPosition: 70, country: "Hungary", femaleLifeExpectancyWeeks: 4209, maleLifeExpectancyWeeks: 3850, },
    { currentPosition: 71, country: "Argentina", femaleLifeExpectancyWeeks: 4196, maleLifeExpectancyWeeks: 3852, },
    { currentPosition: 72, country: "Aruba", femaleLifeExpectancyWeeks: 4127, maleLifeExpectancyWeeks: 3875, },
    { currentPosition: 73, country: "Saint Lucia", femaleLifeExpectancyWeeks: 4073, maleLifeExpectancyWeeks: 3927, },
    { currentPosition: 74, country: "Malaysia", femaleLifeExpectancyWeeks: 4111, maleLifeExpectancyWeeks: 3898, },
    { currentPosition: 75, country: "Brazil", femaleLifeExpectancyWeeks: 4181, maleLifeExpectancyWeeks: 3809, },
    { currentPosition: 76, country: "Romania", femaleLifeExpectancyWeeks: 4169, maleLifeExpectancyWeeks: 3816, },
    { currentPosition: 77, country: "Serbia", femaleLifeExpectancyWeeks: 4125, maleLifeExpectancyWeeks: 3855, },
    { currentPosition: 78, country: "Lithuania", femaleLifeExpectancyWeeks: 4263, maleLifeExpectancyWeeks: 3703, },
    { currentPosition: 79, country: "Brunei", femaleLifeExpectancyWeeks: 4051, maleLifeExpectancyWeeks: 3922, },
    { currentPosition: 80, country: "North Macedonia", femaleLifeExpectancyWeeks: 4087, maleLifeExpectancyWeeks: 3875, },
    { currentPosition: 81, country: "Syria", femaleLifeExpectancyWeeks: 4128, maleLifeExpectancyWeeks: 3816, },
    { currentPosition: 82, country: "Honduras", femaleLifeExpectancyWeeks: 4077, maleLifeExpectancyWeeks: 3839, },
    { currentPosition: 83, country: "Kuwait", femaleLifeExpectancyWeeks: 4021, maleLifeExpectancyWeeks: 3918, },
    { currentPosition: 84, country: "Vietnam", femaleLifeExpectancyWeeks: 4166, maleLifeExpectancyWeeks: 3743, },
    { currentPosition: 85, country: "Latvia", femaleLifeExpectancyWeeks: 4193, maleLifeExpectancyWeeks: 3695, },
    { currentPosition: 86, country: "Saudi Arabia", femaleLifeExpectancyWeeks: 4037, maleLifeExpectancyWeeks: 3886, },
    { currentPosition: 87, country: "Armenia", femaleLifeExpectancyWeeks: 4117, maleLifeExpectancyWeeks: 3747, },
    { currentPosition: 88, country: "Mauritius", femaleLifeExpectancyWeeks: 4118, maleLifeExpectancyWeeks: 3768, },
    { currentPosition: 89, country: "Bulgaria", femaleLifeExpectancyWeeks: 4125, maleLifeExpectancyWeeks: 3759, },
    { currentPosition: 90, country: "Mexico", femaleLifeExpectancyWeeks: 4079, maleLifeExpectancyWeeks: 3789, },
    { currentPosition: 91, country: "Nicaragua", femaleLifeExpectancyWeeks: 4104, maleLifeExpectancyWeeks: 3744, },
    { currentPosition: 92, country: "Belarus", femaleLifeExpectancyWeeks: 4169, maleLifeExpectancyWeeks: 3660, },
    { currentPosition: 93, country: "Belize", femaleLifeExpectancyWeeks: 4083, maleLifeExpectancyWeeks: 3764, },
    { currentPosition: 94, country: "Guatemala", femaleLifeExpectancyWeeks: 4064, maleLifeExpectancyWeeks: 3764, },
    { currentPosition: 95, country: "Jordan", femaleLifeExpectancyWeeks: 4008, maleLifeExpectancyWeeks: 3824, },
    { currentPosition: 96, country: "Jamaica", femaleLifeExpectancyWeeks: 3997, maleLifeExpectancyWeeks: 3818, },
    { currentPosition: 97, country: "Dominican Republic", femaleLifeExpectancyWeeks: 4065, maleLifeExpectancyWeeks: 3735, },
    { currentPosition: 98, country: "State of Palestine", femaleLifeExpectancyWeeks: 3985, maleLifeExpectancyWeeks: 3805, },
    { currentPosition: 99, country: "Paraguay", femaleLifeExpectancyWeeks: 4006, maleLifeExpectancyWeeks: 3785, },
    { currentPosition: 100, country: "Bahamas", femaleLifeExpectancyWeeks: 3992, maleLifeExpectancyWeeks: 3754, },
    { currentPosition: 101, country: "Georgia", femaleLifeExpectancyWeeks: 4098, maleLifeExpectancyWeeks: 3645, },
    { currentPosition: 102, country: "Micronesia", femaleLifeExpectancyWeeks: 4028, maleLifeExpectancyWeeks: 3712, },
    { currentPosition: 103, country: "El Salvador", femaleLifeExpectancyWeeks: 4095, maleLifeExpectancyWeeks: 3614, },
    { currentPosition: 104, country: "Trinidad and Tobago", femaleLifeExpectancyWeeks: 4000, maleLifeExpectancyWeeks: 3717, },
    { currentPosition: 105, country: "Kazakhstan", femaleLifeExpectancyWeeks: 4068, maleLifeExpectancyWeeks: 3629, },
    { currentPosition: 106, country: "Samoa", femaleLifeExpectancyWeeks: 3964, maleLifeExpectancyWeeks: 3741, },
    { currentPosition: 107, country: "Seychelles", femaleLifeExpectancyWeeks: 4055, maleLifeExpectancyWeeks: 3666, },
    { currentPosition: 108, country: "Cabo Verde", femaleLifeExpectancyWeeks: 4009, maleLifeExpectancyWeeks: 3660, },
    { currentPosition: 109, country: "Bangladesh", femaleLifeExpectancyWeeks: 3945, maleLifeExpectancyWeeks: 3746, },
    { currentPosition: 110, country: "Libya", femaleLifeExpectancyWeeks: 3989, maleLifeExpectancyWeeks: 3684, },
    { currentPosition: 111, country: "Solomon Islands", femaleLifeExpectancyWeeks: 3929, maleLifeExpectancyWeeks: 3736, },
    { currentPosition: 112, country: "Azerbaijan", femaleLifeExpectancyWeeks: 3959, maleLifeExpectancyWeeks: 3692, },
    { currentPosition: 113, country: "Russia", femaleLifeExpectancyWeeks: 4078, maleLifeExpectancyWeeks: 3528, },
    { currentPosition: 114, country: "St.Vincent & Grenadines", femaleLifeExpectancyWeeks: 3946, maleLifeExpectancyWeeks: 3687, },
    { currentPosition: 115, country: "North Korea", femaleLifeExpectancyWeeks: 3985, maleLifeExpectancyWeeks: 3614, },
    { currentPosition: 116, country: "Bhutan", femaleLifeExpectancyWeeks: 3826, maleLifeExpectancyWeeks: 3771, },
    { currentPosition: 117, country: "Grenada", femaleLifeExpectancyWeeks: 3922, maleLifeExpectancyWeeks: 3665, },
    { currentPosition: 118, country: "Egypt", femaleLifeExpectancyWeeks: 3911, maleLifeExpectancyWeeks: 3664, },
    { currentPosition: 119, country: "Ukraine", femaleLifeExpectancyWeeks: 4032, maleLifeExpectancyWeeks: 3525, },
    { currentPosition: 120, country: "Bolivia", femaleLifeExpectancyWeeks: 3932, maleLifeExpectancyWeeks: 3626, },
    { currentPosition: 121, country: "Venezuela", femaleLifeExpectancyWeeks: 3978, maleLifeExpectancyWeeks: 3579, },
    { currentPosition: 122, country: "Indonesia", femaleLifeExpectancyWeeks: 3894, maleLifeExpectancyWeeks: 3659, },
    { currentPosition: 123, country: "Moldova", femaleLifeExpectancyWeeks: 3993, maleLifeExpectancyWeeks: 3549, },
    { currentPosition: 124, country: "Suriname", femaleLifeExpectancyWeeks: 3942, maleLifeExpectancyWeeks: 3594, },
    { currentPosition: 125, country: "Uzbekistan", femaleLifeExpectancyWeeks: 3875, maleLifeExpectancyWeeks: 3642, },
    { currentPosition: 126, country: "Kyrgyzstan", femaleLifeExpectancyWeeks: 3967, maleLifeExpectancyWeeks: 3540, },
    { currentPosition: 127, country: "Tajikistan", femaleLifeExpectancyWeeks: 3867, maleLifeExpectancyWeeks: 3626, },
    { currentPosition: 128, country: "Nepal", femaleLifeExpectancyWeeks: 3821, maleLifeExpectancyWeeks: 3659, },
    { currentPosition: 129, country: "Philippines", femaleLifeExpectancyWeeks: 3961, maleLifeExpectancyWeeks: 3531, },
    { currentPosition: 130, country: "Tonga", femaleLifeExpectancyWeeks: 3829, maleLifeExpectancyWeeks: 3615, },
    { currentPosition: 131, country: "Western Sahara", femaleLifeExpectancyWeeks: 3819, maleLifeExpectancyWeeks: 3619, },
    { currentPosition: 131, country: "Iraq", femaleLifeExpectancyWeeks: 3820, maleLifeExpectancyWeeks: 3598, },
    { currentPosition: 132, country: "Sao Tome & Principe", femaleLifeExpectancyWeeks: 3835, maleLifeExpectancyWeeks: 3576, },
    { currentPosition: 133, country: "Vanuatu", femaleLifeExpectancyWeeks: 3796, maleLifeExpectancyWeeks: 3621, },
    { currentPosition: 134, country: "Cambodia", femaleLifeExpectancyWeeks: 3793, maleLifeExpectancyWeeks: 3558, },
    { currentPosition: 135, country: "Mongolia", femaleLifeExpectancyWeeks: 3902, maleLifeExpectancyWeeks: 3466, },
    { currentPosition: 136, country: "India", femaleLifeExpectancyWeeks: 3746, maleLifeExpectancyWeeks: 3609, },
    { currentPosition: 137, country: "Guyana", femaleLifeExpectancyWeeks: 3837, maleLifeExpectancyWeeks: 3507, },
    { currentPosition: 138, country: "Timor - Leste", femaleLifeExpectancyWeeks: 3776, maleLifeExpectancyWeeks: 3555, },
    { currentPosition: 139, country: "Rwanda", femaleLifeExpectancyWeeks: 3765, maleLifeExpectancyWeeks: 3535, },
    { currentPosition: 140, country: "Botswana", femaleLifeExpectancyWeeks: 3793, maleLifeExpectancyWeeks: 3481, },
    { currentPosition: 141, country: "Kiribati", femaleLifeExpectancyWeeks: 3815, maleLifeExpectancyWeeks: 3392, },
    { currentPosition: 142, country: "Laos", femaleLifeExpectancyWeeks: 3694, maleLifeExpectancyWeeks: 3498, },
    { currentPosition: 143, country: "Senegal", femaleLifeExpectancyWeeks: 3698, maleLifeExpectancyWeeks: 3477, },
    { currentPosition: 144, country: "Turkmenistan", femaleLifeExpectancyWeeks: 3767, maleLifeExpectancyWeeks: 3397, },
    { currentPosition: 145, country: "Micronesia", femaleLifeExpectancyWeeks: 3656, maleLifeExpectancyWeeks: 3472, },
    { currentPosition: 146, country: "Madagascar", femaleLifeExpectancyWeeks: 3648, maleLifeExpectancyWeeks: 3471, },
    { currentPosition: 147, country: "Fiji", femaleLifeExpectancyWeeks: 3651, maleLifeExpectancyWeeks: 3444, },
    { currentPosition: 148, country: "Djibouti", femaleLifeExpectancyWeeks: 3661, maleLifeExpectancyWeeks: 3435, },
    { currentPosition: 149, country: "Ethiopia", femaleLifeExpectancyWeeks: 3642, maleLifeExpectancyWeeks: 3436, },
    { currentPosition: 150, country: "Pakistan", femaleLifeExpectancyWeeks: 3595, maleLifeExpectancyWeeks: 3484, },
    { currentPosition: 151, country: "Myanmar", femaleLifeExpectancyWeeks: 3695, maleLifeExpectancyWeeks: 3373, },
    { currentPosition: 152, country: "Eritrea", femaleLifeExpectancyWeeks: 3639, maleLifeExpectancyWeeks: 3405, },
    { currentPosition: 153, country: "Kenya", femaleLifeExpectancyWeeks: 3646, maleLifeExpectancyWeeks: 3394, },
    { currentPosition: 154, country: "Gabon", femaleLifeExpectancyWeeks: 3614, maleLifeExpectancyWeeks: 3388, },
    { currentPosition: 155, country: "Yemen", femaleLifeExpectancyWeeks: 3556, maleLifeExpectancyWeeks: 3377, },
    { currentPosition: 156, country: "Tanzania", femaleLifeExpectancyWeeks: 3561, maleLifeExpectancyWeeks: 3366, },
    { currentPosition: 157, country: "Sudan", femaleLifeExpectancyWeeks: 3550, maleLifeExpectancyWeeks: 3349, },
    { currentPosition: 158, country: "Afghanistan", femaleLifeExpectancyWeeks: 3527, maleLifeExpectancyWeeks: 3364, },
    { currentPosition: 159, country: "Malawi", femaleLifeExpectancyWeeks: 3588, maleLifeExpectancyWeeks: 3258, },
    { currentPosition: 160, country: "Mauritania", femaleLifeExpectancyWeeks: 3508, maleLifeExpectancyWeeks: 3333, },
    { currentPosition: 161, country: "Papua New Guinea", femaleLifeExpectancyWeeks: 3476, maleLifeExpectancyWeeks: 3335, },
    { currentPosition: 162, country: "Congo", femaleLifeExpectancyWeeks: 3482, maleLifeExpectancyWeeks: 3322, },
    { currentPosition: 163, country: "Comoros", femaleLifeExpectancyWeeks: 3490, maleLifeExpectancyWeeks: 3300, },
    { currentPosition: 164, country: "Liberia", femaleLifeExpectancyWeeks: 3469, maleLifeExpectancyWeeks: 3315, },
    { currentPosition: 165, country: "Haiti", femaleLifeExpectancyWeeks: 3507, maleLifeExpectancyWeeks: 3275, },
    { currentPosition: 166, country: "Ghana", femaleLifeExpectancyWeeks: 3450, maleLifeExpectancyWeeks: 3328, },
    { currentPosition: 167, country: "South Africa", femaleLifeExpectancyWeeks: 3570, maleLifeExpectancyWeeks: 3207, },
    { currentPosition: 168, country: "Namibia", femaleLifeExpectancyWeeks: 3531, maleLifeExpectancyWeeks: 3226, },
    { currentPosition: 169, country: "Zambia", femaleLifeExpectancyWeeks: 3533, maleLifeExpectancyWeeks: 3217, },
    { currentPosition: 170, country: "Uganda", femaleLifeExpectancyWeeks: 3479, maleLifeExpectancyWeeks: 3234, },
    { currentPosition: 171, country: "Niger", femaleLifeExpectancyWeeks: 3386, maleLifeExpectancyWeeks: 3256, },
    { currentPosition: 172, country: "Gambia", femaleLifeExpectancyWeeks: 3377, maleLifeExpectancyWeeks: 3225, },
    { currentPosition: 173, country: "Burkina Faso", femaleLifeExpectancyWeeks: 3328, maleLifeExpectancyWeeks: 3238, },
    { currentPosition: 174, country: "Benin", femaleLifeExpectancyWeeks: 3363, maleLifeExpectancyWeeks: 3195, },
    { currentPosition: 175, country: "Burundi", femaleLifeExpectancyWeeks: 3369, maleLifeExpectancyWeeks: 3175, },
    { currentPosition: 176, country: "Guinea", femaleLifeExpectancyWeeks: 3300, maleLifeExpectancyWeeks: 3224, },
    { currentPosition: 177, country: "Angola", femaleLifeExpectancyWeeks: 3398, maleLifeExpectancyWeeks: 3102, },
    { currentPosition: 178, country: "Zimbabwe", femaleLifeExpectancyWeeks: 3322, maleLifeExpectancyWeeks: 3151, },
    { currentPosition: 179, country: "Togo", femaleLifeExpectancyWeeks: 3291, maleLifeExpectancyWeeks: 3191, },
    { currentPosition: 179, country: "Mozambique", femaleLifeExpectancyWeeks: 3389, maleLifeExpectancyWeeks: 3081, },
    { currentPosition: 180, country: "DR Congo", femaleLifeExpectancyWeeks: 3298, maleLifeExpectancyWeeks: 3131, },
    { currentPosition: 181, country: "Eswatini", femaleLifeExpectancyWeeks: 3426, maleLifeExpectancyWeeks: 2973, },
    { currentPosition: 182, country: "Mali", femaleLifeExpectancyWeeks: 3203, maleLifeExpectancyWeeks: 3114, },
    { currentPosition: 183, country: "Cameroon", femaleLifeExpectancyWeeks: 3217, maleLifeExpectancyWeeks: 3078, },
    { currentPosition: 184, country: "Equatorial Guinea", femaleLifeExpectancyWeeks: 3187, maleLifeExpectancyWeeks: 3066, },
    { currentPosition: 185, country: "Guinea - Bissau", femaleLifeExpectancyWeeks: 3200, maleLifeExpectancyWeeks: 2990, },
    { currentPosition: 186, country: "Côte d'Ivoire", femaleLifeExpectancyWeeks: 3137, maleLifeExpectancyWeeks: 3000, },
    { currentPosition: 187, country: "South Sudan", femaleLifeExpectancyWeeks: 3147, maleLifeExpectancyWeeks: 2985, },
    { currentPosition: 188, country: "Somalia", femaleLifeExpectancyWeeks: 3136, maleLifeExpectancyWeeks: 2954, },
    { currentPosition: 189, country: "Sierra Leone", femaleLifeExpectancyWeeks: 2963, maleLifeExpectancyWeeks: 2870, },
    { currentPosition: 190, country: "Nigeria", femaleLifeExpectancyWeeks: 2961, maleLifeExpectancyWeeks: 2859, },
    { currentPosition: 191, country: "Lesotho", femaleLifeExpectancyWeeks: 3073, maleLifeExpectancyWeeks: 2740, },
    { currentPosition: 192, country: "Chad", femaleLifeExpectancyWeeks: 2956, maleLifeExpectancyWeeks: 2803, },
    { currentPosition: 193, country: "Central African Republic", femaleLifeExpectancyWeeks: 2952, maleLifeExpectancyWeeks: 2722, },
]